### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by haxzie**
- Added additional folder structure for lab experiments with multiple files.
- Added Managed by Probot badge

### CODE REVIEW

**Comment by Hitoshirenu** [comment]
> This is a fresh patch directly from GitHub. Is there a pending PR for the proposed structure?

https://github.com/so-sc/VTU-Lab-Material/tree/master/sem-7/computer_science/15CSL77_WEB_TECHNOLOGY_LABORATORY_WITH_MINI_PROJECT

You sure? Look like you're on your old fork and not pulled changes from upstream and merged with you repos master.

**Comment by haxzie** [comment]
It doesn't matter since the only file that's been changed is the README.md file of the repo. Plus this PR isn't from a separate fork, it's just a branch within this repo.

**Comment by Hitoshirenu** [comment]
> It doesn't matter since the only file that's been changed is the README.md file of the repo. Plus this PR isn't from a separate fork, it's just a branch within this repo.

No what i mean was in your file structure you put it as 
```sh
.
├── sem-7
│   ├── computer_science
│   │   ├── 15CSL77_WEB_PROGRAMMING_LABORATORY
│   │   │   ├── 01 Calculator
│   │   │   |   ├── index.html
│   │   │   |   ├── style.css
.   .   .   .   .
.   .   .   .   .
```
Which confused me because the current file structure was different. I guess it can be anything. I thought it would look better if it mapped to the actual repo structure like

```sh
.
├── sem-7
│   ├── computer_science
│   │   ├── 15CSL77_WEB_PROGRAMMING_LABORATORY
 .   .    .    .
 |   |    |   ├── program-05
│   │   │   |   ├── index.xml
│   │   │   |   ├── style.css
.   .   .   .   .
.   .   .   .   .
```
But i think it's fine anyways, Sorry for the confusion :man_facepalming: 
Additionally i think this information better resides in the CONTRIBUTING.md :beers:

**Comment by haxzie** [comment]
I guess, instead of naming the program files with the entire program name, It'd be better to move the files into separate folders and use standard naming conventions. This will be extremely necessary when it comes to Java Programs too.

**Comment by Hitoshirenu** [comment]
> I guess, instead of naming the program files with the entire program name, It'd be better to move the files into separate folders and use standard naming conventions. This will be extremely necessary when it comes to Java Programs too.

Example?

**Comment by Hitoshirenu** [comment]
Found a typo at 'seprate', Everything else looks good for a merge.

**Comment by haxzie** [comment]
Fixed all typos and Updated Contributing.md, I think we are Good to Go :+1:

**Pull request merged**
