### PR TITLE
spellcheck & created output files 

### PR DESCRIPTION
**Pull request by nathanielmathew**
grammatical correction and created readme.md output files under sem-3/CS/DSlab programs

### CODE REVIEW

**Comment by nathanielmathew** [comment]
Sure, 
1)added a readme.md output file, to write the output into,  for each lab program in sem 3 
2)minor grammatical corrections in the main readme
3)Added the output of program 12 in sem3/DSLab
4)Did a bit of formatting on program 1 of DSLab
5)sem3/DSLab now has all the lab program questions + how to execute them in its readme.md file

**Comment by haxzie** [comment]
Cool, I'll be merging the PR now. Please keep in mind, while fixing grammatical errors, Do not cut/paste the contents of the entire file, Just go line by line, that makes the review a lot easier :smile: :+1:

**Comment by suhanacharya** [comment]
Umm, why did every file's commit message change to _**"spellcheck & created output files"**_? :confused:

**Comment by nathanielmathew** [comment]
Sorry that was My bad. Long story

**Comment by haxzie** [comment]
It's because Ryan changed contents of every file with his spell checked version marking all the files as new one. @nathanielmathew please don't repeat this again 😂 you don't have to spell check the LISENCE, it's automatically generated.

**Comment by nathanielmathew** [comment]
I didn't 😂 I ended up deleting and restoring the whole repository because of some issues on my end, hence the commit message on all the files. Won't happeb again

**Pull request merged**
